### ISSUE TITLE
feat: add tests

### ISSUE THREAD

**Issue by gershon** [ArkProjectNFTs/ark-market#164] opened 2024-09-25 10:27 UTC
### Describe the feature you'd like to request

We should add some tests.

### Describe the solution you'd like to see

Setup test tooling for react / unit tests using vitest, and write some/few tests (coverage target will be defined later).

**Comment by ShantelPeters** [comment] 2024-09-25 19:30
Please can i be assigned to this issue @gershon

**Comment by JoE11-y** [comment] 2024-09-26 08:13
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
With over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
Study the codebase, and implement tests to ensure close to 100% coverage

**Comment by lauchaves** [comment] 2024-09-26 08:20
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Hi! I'm Lau Chaves, and I would like to contribute to this issue!

I have over 5 years of experience working with JavaScript, React, TypeScript, and Ruby. I'm also part of Dojo Coding Costa Rica!

I have knowledge of testing React components and logic using Jest, and I believe implementing Vitest should be pretty similar, so I'm confident I can handle that. 

Feel free to check my onlydust profile here and github profile: lauchaves!

### How I plan on tackling this issue
I'd follow this approach:

- Set up test tooling for React/unit tests using Vitest. (configure it and set up testing environment)
- Write some initial tests (will define which initial tests I should add with the maintainers).

**Comment by Ugo-X** [comment] 2024-09-26 08:30
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will add tests to the project as follows:

I will set up Vitest for React and unit testing:
I will install Vitest and related dependencies.
I will configure Vitest in the project, setting up test scripts in package.json.

I will create a basic test structure:
I will set up a __tests__ directory or test files alongside components.
I will write a simple test for a core component to ensure setup is correct.

I will implement a few key unit tests:
I will identify critical functions or components to test.
I will write tests for these, focusing on important functionality.

I will set up a basic CI pipeline:
I will configure GitHub Actions or similar to run tests on push/PR.

I will document the testing approach for future expansion.

**Comment by No-bodyq** [comment] 2024-09-26 09:12
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I am a computer science student, fullstack and web3 dev. I have contributed to a couple of open source projects in the past via only dust

### How I plan on tackling this issue
I'll begin by analyzing the code to pinpoint all functions that need unit tests. Then I'll configure Vitest for unit testing, making sure it integrates seamlessly with the existing project setup. After that I'll create tests for each identified function, covering standard scenarios as well as edge cases to ensure thorough test coverage. Lastly, I'll execute the tests and validate their results to ensure they function correctly and offer meaningful insights into any potential issues.

**Comment by martinvibes** [comment] 2024-09-26 09:19
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged

hello i am a frontend dev and smart contract developer
please can i work on this issue :) and would love to be a contributor

**Comment by abdegenius** [comment] 2024-09-26 13:27
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I am a skilled fullstack developer with a wealth of experience in both frontend and backend JavaScript as well as my knowledge of Rustlang, With a solid foundation in testing,I have mastered frameworks like Mocha, Chai, and Jest to ensure robust, reliable code in every project. In addition to traditional web development, I have a strong background in blockchain technology, with hands-on experience in Solidity for Ethereum-based smart contracts. Moreover, I have delved into the emerging world of StarkNet, working with Cairo, a cutting-edge language tailored for STARKs, making them a versatile developer capable of bridging both traditional and decentralized web applications.

### How I plan on tackling this issue
Will install vitest as a test library, setup the tests and write necessary test cases as well as update package.json with the appropriate test commands

**Comment by kwiss** [comment] 2024-09-27 07:19
please proceed with it @coxmars

**Comment by coxmars** [comment] 2024-09-30 01:39
Hi @gershon @kwiss, I was reviewing the codebase and yesterday I wanted to setup the testing env, reading more about in the docs like https://nextjs.org/docs/app/building-your-application/testing/vitest and https://vitest.dev/guide/ but I'm getting this error, do you know how can I solve that? 

I tried with these:

```
pnpm install -Dw vitest @vitest/ui @testing-library/react @testing-library/jest-dom jsdom @vitejs/plugin-react
pnpm add -Dw vitest @vitest/ui @testing-library/react @testing-library/jest-dom jsdom @vitejs/plugin-react
```

And I got the same error, can you help me with this? I thing this is the only block, after that I will not have problems

```
ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @types/react@catalog:react18 isn't supported by any available resolver.

This error happened while installing a direct dependency of
```

![telegram-cloud-photo-size-1-5170530911282900407-y](https://github.com/user-attachments/assets/2562bbe4-fbce-4436-a201-6afdbb8cbded)

**Comment by coxmars** [comment] 2024-10-02 15:40
Hi @gershon, thanks for the suggestion, but I’m still encountering an issue with the catalog:react18 resolver. It seems pnpm can’t resolve dependencies with catalog:. Is there any additional setup or configuration needed to resolve catalog: dependencies correctly?

``arkmarket dir/root:``

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/1315e86b-aafb-4d3f-b669-244ca81388cf">

- I tested with other NextJS projects etc and it is working as expected so the issue is specific for this projects structure.
- This is the only block, add the unit tests will be faster and I can provide you at least 10-15 but this is the delay for the moment.

**Comment by gershon** [comment] 2024-10-02 16:31
Ok that's weird, I just cloned the repo, installed existing deps and installed vitest without any errors.

```bash
git clone git@github.com:ArkProjectNFTs/ark-market.git && cd ark-market;
pnpm install;
cd apps/arkmarket;
pnpm add -D vitest
```

Can you test this install flow and lmk if you still have errors.

**Comment by coxmars** [comment] 2024-10-02 17:40
> Ok that's weird, I just cloned the repo, installed existing deps and installed vitest without any errors.
> 
> ```shell
> git clone git@github.com:ArkProjectNFTs/ark-market.git && cd ark-market;
> pnpm install;
> cd apps/arkmarket;
> pnpm add -D vitest
> ```
> 
> Can you test this install flow and lmk if you still have errors.

Thanks for the guidance sir, I tried to follow the flow but I'm still having the same problem as you can see.

Do you have others tools installed neccesary to run this succesfully? Maybe specific versions etc?

<img width="1505" alt="image" src="https://github.com/user-attachments/assets/c76ecba7-4bc6-4709-b5ca-b86d7d0b62de">

-  Also I'm executing this in a fork from the original repo, using the last commit too.

<img width="1505" alt="image" src="https://github.com/user-attachments/assets/e185eda3-d92d-4f30-b011-6da03979a4af">

- Currently, I'm using MacOS so I will test in my PC (Windows) for the moment.

**Comment by gershon** [comment] 2024-10-02 19:52
You might find a solution here https://github.com/pnpm/pnpm/issues/5134. You can try one of these: 
- update pnpm to latest version (i'm using `9.5.0`)
- delete `pnpm-lock.yaml` and re generate it via `pnpm i`

**Comment by coxmars** [comment] 2024-10-02 20:16
> You might find a solution here https://github.com/pnpm/pnpm/issues/5134. You can try one of these: 
> - update pnpm to latest version (i'm using `9.5.0`)
> - delete `pnpm-lock.yaml` and re generate it via `pnpm i`

Thanks sir I will do it asap and I will let you know 👍🏻

**Comment by coxmars** [comment] 2024-10-02 22:08
> You might find a solution here [pnpm/pnpm#5134](https://github.com/pnpm/pnpm/issues/5134). You can try one of these:
> 
> * update pnpm to latest version (i'm using `9.5.0`)
> * delete `pnpm-lock.yaml` and re generate it via `pnpm i`

I solved the problem sir, I had an old pnpm version so now I'm using the latest 9.12.0 and it is working. I will start with the issue and I will send a PR asap 🫡

![telegram-cloud-photo-size-1-5184116326631845143-y](https://github.com/user-attachments/assets/ab19719c-4703-4e5e-b921-b12587124033)

**Closed** 2024-10-05 12:34 UTC
Labels: ODHack8
